### ISSUE TITLE
Тесты Никиты

### ISSUE THREAD

**Issue by LionZXY** [glitchless/homework-4#1]
- [x] Можно прикрепить видео к посту
- [x] Можно прикрепить видео к личному сообщению
- [x] При нажатии вкладок разделы переключаются
- [x] Поиск видео работает
- [x] Видео открывается
- [x] Стрим открывается
- [x] Можно оставить комментарий к стриму
- [x] Можно оставить комментарий к видео
- [x] Видео загружается, После загрузки видео попадает в вкладку "Моё видео"
- [x] Подписаться на канал, в моих подписках видео каналов, на которые ты подписан

**Comment by Ansile** [comment]
@LionZXY О, хорошая идея
